# Generated by Django 2.2.5 on 2019-12-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emikoKanri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserecord',
            name='urine_time',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='nurserecord',
            name='urine_volume',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
